### ISSUE TITLE
add image.placeholder.color support for css placeholder

### ISSUE THREAD

**Issue by sean-pwd** [future-wd/hugo-image#13]
## 2. Native lazy loading, no JS scripts, no Inline Styles, solid color placeholder

``` YAML
image:
  placeholder:
    style: color
    color: "#eee"
    type: css 
  lazyLibrary:
    enable: false
```
