### ISSUE TITLE
research merging of module config and update the following

### ISSUE THREAD

**Issue by sean-au** [future-wd/hugo-image#4]
current /config/_default/params.yaml
lazy library functionality is another issue

``` YAML
image:
  format: ["webp", "original"]
  placeholder: blur
    # nativePlaceholder: none or colour value
    # libraryPlaceholder: blur, none, colour
  loading: lazy
  minWidth: 500
  maxWidth: 4000
  deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840]
  imageSizes: [16, 32, 48, 64, 96, 128, 256, 384]
  linkClass: ""
figure:
  class: figure # a class must be set here for lazylibrary.figureCSS to target figures
  titleClass: h4
  imageClass: figure-img
  figcaptionClass: figure-caption
  attrLinkClass: ""
lazyLibrary:
  enabled: false
  dataSrcSet: true
  dataSrc: false
  dataSizes: true
  #  imageCSS: "display:block;width:100%;" # add to css, but configure here?
  imageClass: lazysizes # option of array
  #  figureCSS: "display:block!important;" # add to css, but configure here? img.image and figure.[figure.class] (takes )
  noscript: false
```
